# # The following line prevents the package from being accidentally published to
# # pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev



#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   flutter_lints: ^5.0.0


# # The following section is specific to Flutter packages.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true


#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/to/resolution-aware-images



#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/to/font-from-package





name: learnarabickids
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.3
  # cloud_firestore: ^5.6.0
  # cloud_functions: ^5.2.0
  # firebase_analytics: ^11.3.6
  # firebase_auth: ^5.3.4
  # firebase_core: ^3.9.0
  # firebase_crashlytics: ^4.2.0
  # firebase_remote_config: ^5.2.0
  # firebase_storage: ^12.3.7
  # firebase_ui_auth: ^1.16.0
  # firebase_ui_localizations: ^1.13.0
  # firebase_ui_oauth_google: ^1.4.0
  flutter_localizations:
      sdk: flutter
  hooks_riverpod: ^2.6.1
  responsive_framework: ^1.5.1
  sentry_flutter: ^8.12.0
  flutter_chat_bubble: ^2.0.2
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  chewie: ^1.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/videos/



flutter_launcher_icons:
  android: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    background_color: "#8ACDEA"
    theme_color: "#8ACDEA"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/ic_launcher.png"

     
    sdk: flutter
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true